# -*- coding: utf-8 -*-
"""ChampionsLeagueSimulation_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fv_uomZOzCTKAnvZMZu9FYfgezxaFfUC
"""



#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Champions League Final Simulation (Threads & Locks Demo)
MIT — Operating Systems / Parallel Computing

New rules implemented:
- Fouls only against current ball-holder; if holder is FWD, exactly one DEF/MID from the other team may foul.
- Penalty on FWD being fouled pauses all threads; shot taken, then resume.
- After any goal, ball to a MID of the conceding (other) team.
- Match streakers: 0.01% per tick per fan; pause → remove → resume with last owner.
"""

import threading
import time
import random
from enum import Enum

# ---------------------------
# Utilities
# ---------------------------

print_lock = threading.Lock()
t0 = time.time()

def log(msg):
    with print_lock:
        now = time.time() - t0
        print(f"[{now:6.2f}s] {msg}")

# ---------------------------
# Domain Enums & Config
# ---------------------------

class Role(Enum):
    GK = "GK"
    DEF = "DEF"
    MID = "MID"
    FWD = "FWD"

TICK_SECONDS = 5                  # 5 seconds = 5 minutes
MATCH_TICKS = 18                  # 90 minutes total
NUM_FANS = 50
TEAM_SIZE = 11

# Probabilities (tweak if you like)
PROB_FOUL_DEF = 0.10              # DEF fouls (only when FWD has ball)
PROB_FOUL_MID = 0.06              # MID fouls (only when FWD has ball)
PROB_STEAL_FWD_BY_DEF_OR_GK = 0.20
PROB_STEAL_MID_BY_MID = 0.12
PROB_STEAL_DEF_BY_FWD = 0.18
PROB_SHOT_FWD = 0.25              # FWD with ball chooses shot vs pass
PROB_SAVE_BY_GK = 0.55            # GK save chance if shot on target
PROB_SHOT_ON_TARGET = 0.65
PROB_QUEUE_VISIT = 0.75           # fan decides to buy food (pre-match)
PROB_BUY_SOMETHING = 0.85

# Streakers
PROB_STREAK_PREGAME = 0.0         # disable pregame streaks for clarity
PROB_STREAK_MATCH = 0.0001        # 0.01% per fan per tick

# Shop config
SHOP_STOCK = {"pies": 60, "sodas": 90, "scarves": 30}
SHOP_QUEUE_MAX = 12
CASHIERS = 2

random.seed(7)

# ---------------------------
# Global match control
# ---------------------------

class Stadium:
    def __init__(self):
        self.gates_open = threading.Event()
        self.anthem_start = threading.Event()
        self.match_start = threading.Event()

stadium = Stadium()

tick_event = threading.Event()    # pulsed once per tick
end_event = threading.Event()     # set when match is over
pause_event = threading.Event()   # set = play, clear = paused (penalty/streak/etc.)
pause_event.set()

stoppage_lock = threading.Lock()  # serializes stoppages (penalties or streaks)
foul_lock = threading.Lock()      # ensures one foul occurrence per incident

# ---------------------------
# Shop (Critical Regions)
# ---------------------------

class Shop:
    def __init__(self, stock, queue_max, cashiers):
        self.stock = dict(stock)
        self.stock_lock = threading.Lock()
        self.queue_slots = threading.Semaphore(queue_max)
        self.cashiers = threading.Semaphore(cashiers)

    def enter_queue(self, fan_name):
        log(f"🧍 {fan_name} attempts to enter food queue.")
        self.queue_slots.acquire()
        log(f"🧍 {fan_name} entered the food queue.")

    def leave_queue(self, fan_name):
        self.queue_slots.release()
        log(f"🏃 {fan_name} leaves the food queue.")

    def buy(self, fan, item, price):
        with self.cashiers:
            with self.stock_lock:
                if self.stock.get(item, 0) <= 0:
                    log(f"💥 {fan.name} tried to buy {item}, but it's OUT OF STOCK.")
                    return False
                if fan.money < price:
                    log(f"💸 {fan.name} cannot afford {item} (${price}).")
                    return False
                self.stock[item] -= 1
                fan.money -= price
                log(f"🧾 {fan.name} bought {item} for ${price}. Remaining ${fan.money}.")
                return True

shop = Shop(SHOP_STOCK, SHOP_QUEUE_MAX, CASHIERS)

# ---------------------------
# Teams, Players, Ball
# ---------------------------

class Team:
    def __init__(self, name):
        self.name = name
        self.players = []
        self.arrival_barrier = threading.Barrier(TEAM_SIZE)
        self.field_barrier = threading.Barrier(TEAM_SIZE)

class Ball:
    """
    Critical region for ball actions: mutex.
    'possession_lock' protects owner pointer.
    """
    def __init__(self):
        self.mutex = threading.Lock()
        self.possession_lock = threading.Lock()
        self.owner = None
        self.last_team = None

    def set_owner(self, player):
        with self.possession_lock:
            self.owner = player
            self.last_team = player.team.name
            log(f"⚽ Ball now with {player}.")

    def get_owner(self):
        with self.possession_lock:
            return self.owner

ball = Ball()

score_lock = threading.Lock()
scoreboard = {"A": 0, "B": 0}

# ---------------------------
# Choir / Anthem
# ---------------------------

ANTHEM_LINES = [
    "♪ The night is bright, the crowd ignites,",
    "♪ Eleven hearts in blue and white,",
    "♪ Eleven hearts in red and gold,",
    "♪ The final’s tale is to be told!",
]

# ---------------------------
# Clock
# ---------------------------

class MatchClock(threading.Thread):
    def __init__(self, tick_event, end_event):
        super().__init__(daemon=True)
        self.tick_event = tick_event
        self.end_event = end_event
        self.current_tick = 0

    def run(self):
        stadium.match_start.wait()
        log("⏱️ Match clock starts.")
        while self.current_tick < MATCH_TICKS and not self.end_event.is_set():
            # Respect global pause
            pause_event.wait()
            # Sleep for the tick duration (also pauses if paused mid-sleep)
            start = time.time()
            while True:
                remaining = TICK_SECONDS - (time.time() - start)
                if remaining <= 0: break
                pause_event.wait(timeout=min(0.1, remaining))
                if self.end_event.is_set():
                    break
            if self.end_event.is_set(): break

            self.current_tick += 1
            log(f"⏱️ Tick {self.current_tick}/{MATCH_TICKS}")
            # Pulse tick event
            self.tick_event.set()
            time.sleep(0.03)
            self.tick_event.clear()

        log("⏱️ Match clock ends.")
        self.end_event.set()

# ---------------------------
# Fans
# ---------------------------

class Fan(threading.Thread):
    def __init__(self, idx):
        super().__init__(daemon=True)
        self.name = f"Fan-{idx:02d}"
        self.money = random.randint(5, 50)

    def maybe_streak_pregame(self):
        if PROB_STREAK_PREGAME > 0 and random.random() < PROB_STREAK_PREGAME:
            log(f"🫣 {self.name} runs naked pregame! Security scrambles!")
            time.sleep(0.4)
            log(f"🛡️ Security escorts {self.name} away.")

    def streak_during_match_loop(self):
        stadium.match_start.wait()
        last_owner = None
        while not end_event.is_set():
            # Wake each tick, decide if this fan streaks
            self_tick_seen = tick_event.wait(timeout=0.5)
            if not self_tick_seen:
                continue
            if random.random() < PROB_STREAK_MATCH:
                # Try to initiate a stoppage (only one at a time)
                if stoppage_lock.acquire(blocking=False):
                    try:
                        if not pause_event.is_set():
                            continue  # already paused for another reason
                        # Pause play
                        pause_event.clear()
                        last_owner = ball.get_owner()
                        log(f"🫣 {self.name} streaks onto the field! Players stop!")
                        time.sleep(1.2)  # removal time
                        if last_owner:
                            ball.set_owner(last_owner)
                        log(f"🛡️ Security removed {self.name}. Play resumes.")
                        pause_event.set()
                    finally:
                        stoppage_lock.release()

    def run(self):
        log(f"🚶 {self.name} heading to stadium.")
        stadium.gates_open.wait()
        log(f"🚪 {self.name} enters the stadium.")

        time.sleep(random.uniform(0.1, 0.6))
        # Optional pregame shopping
        if random.random() < PROB_QUEUE_VISIT:
            shop.enter_queue(self.name)
            time.sleep(random.uniform(0.1, 0.5))
            if random.random() < PROB_BUY_SOMETHING:
                choice = random.choice(list(SHOP_STOCK.keys()))
                price = {"pies": 8, "sodas": 5, "scarves": 15}[choice]
                shop.buy(self, choice, price)
            shop.leave_queue(self.name)

        time.sleep(random.uniform(0.1, 0.5))
        self.maybe_streak_pregame()

        # During match, listen for ticks and maybe streak
        self.streak_during_match_loop()

# ---------------------------
# Player helpers
# ---------------------------

def role_str(role: Role):
    return role.value

def allowed_pass_targets(player):
    if player.role == Role.FWD:
        return [Role.FWD, Role.MID]          # horizontal/back
    if player.role == Role.MID:
        return [Role.FWD, Role.MID, Role.DEF]
    if player.role == Role.DEF:
        return [Role.MID, Role.DEF, Role.GK]
    if player.role == Role.GK:
        return [Role.DEF, Role.MID, Role.FWD]
    return []

def can_steal(attacker, owner):
    if owner is None or attacker.team.name == owner.team.name:
        return False, 0.0
    if owner.role == Role.FWD and attacker.role in (Role.DEF, Role.GK):
        return True, PROB_STEAL_FWD_BY_DEF_OR_GK
    if owner.role == Role.MID and attacker.role == Role.MID:
        return True, PROB_STEAL_MID_BY_MID
    if owner.role == Role.DEF and attacker.role == Role.FWD:
        return True, PROB_STEAL_DEF_BY_FWD
    return False, 0.0

def choose_midfielder(team):
    mids = [p for p in team.players if p.role == Role.MID]
    if mids:
        return random.choice(mids)
    # fallback if roster shuffled oddly
    non_gk = [p for p in team.players if p.role != Role.GK]
    return random.choice(non_gk) if non_gk else team.players[0]

def restart_after_goal(scoring_team):
    """After any goal, give ball to a MIDFIELDER of the other team."""
    other = teamA if scoring_team.name == "B" else teamB
    mid = choose_midfielder(other)
    ball.set_owner(mid)
    log(f"🔁 Kickoff: {other.name} restarts via {mid}.")

# ---------------------------
# Player Thread
# ---------------------------

class Player(threading.Thread):
    def __init__(self, team, name, role, team_arrival_barrier, field_barrier):
        super().__init__(daemon=True)
        self.team = team
        self.pname = name
        self.role = role
        self.team_arrival_barrier = team_arrival_barrier
        self.field_barrier = field_barrier

    def __str__(self):
        return f"{self.team.name}-{self.pname}({role_str(self.role)})"

    # --- Ball actions ---

    def pass_ball(self):
        roles = allowed_pass_targets(self)
        candidates = [p for p in self.team.players if p is not self and p.role in roles]
        if not candidates:
            return None
        target = random.choice(candidates)
        ball.set_owner(target)
        log(f"➡️  {self} passes to {target}.")
        return target

    def consider_shot(self):
        if self.role != Role.FWD:
            return False
        if random.random() < PROB_SHOT_FWD:
            # Shot decision
            on_target = random.random() < PROB_SHOT_ON_TARGET
            other_team = teamA if self.team.name == "B" else teamB
            gk = [p for p in other_team.players if p.role == Role.GK][0]
            if on_target:
                if random.random() < PROB_SAVE_BY_GK:
                    log(f"🧤 Shot by {self} ON TARGET! Saved by {gk}!")
                    ball.set_owner(gk)
                else:
                    with score_lock:
                        scoreboard[self.team.name] += 1
                    log(f"🥅 GOAL! {self} scores!  Score: {scoreboard['A']} - {scoreboard['B']}")
                    restart_after_goal(self.team)
            else:
                log(f"🎯 Shot by {self} is OFF target. Goal kick to {gk}.")
                ball.set_owner(gk)
            return True
        return False

    # --- Fouls only against FWD owner ---

    def attempt_foul_on_forward_owner(self):
        """
        If the current owner is a Forward, allow at most one opposing DEF/MID to foul.
        This triggers a penalty and pauses play.
        """
        # Only eligible roles can foul
        if self.role not in (Role.DEF, Role.MID):
            return
        owner = ball.get_owner()
        if (owner is None or owner.team.name == self.team.name or owner.role != Role.FWD):
            return

        # Try to become the single fouler for this incident
        if not foul_lock.acquire(blocking=False):
            return

        committed = False
        try:
            # Re-check consistency just before committing
            owner_now = ball.get_owner()
            if owner_now is not owner or not pause_event.is_set():
                return
            # Role-based foul probability
            p = PROB_FOUL_DEF if self.role == Role.DEF else PROB_FOUL_MID
            if random.random() < p:
                committed = True
                log(f"🟨 {self} fouls {owner}! PENALTY to Team {owner.team.name}!")
                self.handle_penalty(fouled_forward=owner)
        finally:
            # Hold the lock through the penalty; otherwise release immediately
            if not committed:
                foul_lock.release()

    def handle_penalty(self, fouled_forward):
        """Pause everyone, take the penalty, assign post-outcome possession, resume."""
        # Serialise with other stoppages
        stoppage_lock.acquire()
        try:
            # Pause the world
            pause_event.clear()
            log("⏸️  Play paused for penalty setup.")
            time.sleep(0.8)  # setup time

            # Penalty taker = fouled forward's team (could be the same forward)
            shooting_team = fouled_forward.team
            other_team = teamA if shooting_team.name == "B" else teamB
            gk = [p for p in other_team.players if p.role == Role.GK][0]

            # Penalty shot (use same on-target/save params)
            on_target = random.random() < PROB_SHOT_ON_TARGET
            if on_target and random.random() >= PROB_SAVE_BY_GK:
                with score_lock:
                    scoreboard[shooting_team.name] += 1
                log(f"🥅 PENALTY GOAL by {fouled_forward}! Score: {scoreboard['A']} - {scoreboard['B']}")
                restart_after_goal(shooting_team)
            else:
                # saved or off target -> GK possession
                if on_target:
                    log(f"🧤 Penalty by {fouled_forward} SAVED by {gk}!")
                else:
                    log(f"🎯 Penalty by {fouled_forward} OFF target. {gk} restarts.")
                ball.set_owner(gk)

            time.sleep(0.4)
            log("▶️  Play resumes after penalty.")
            pause_event.set()
        finally:
            stoppage_lock.release()
            foul_lock.release()

    # --- Steals ---

    def attempt_steal_window(self):
        owner = ball.get_owner()
        allowed, p = can_steal(self, owner)
        if not allowed or not pause_event.is_set():
            return
        if random.random() < p:
            got = ball.mutex.acquire(timeout=0.01)
            if got:
                try:
                    if ball.get_owner() is owner and pause_event.is_set():
                        ball.set_owner(self)
                        log(f"🧨 STEAL! {self} dispossesses {owner}.")
                finally:
                    ball.mutex.release()

    def ball_handler_tick(self):
        if not pause_event.is_set():
            return
        got = ball.mutex.acquire(timeout=0.05)
        if not got:
            return
        try:
            if ball.get_owner() is not self or not pause_event.is_set():
                return
            # Shot (FWD only) else pass
            if not self.consider_shot():
                self.pass_ball()
        finally:
            ball.mutex.release()

    # --- Lifecycle ---

    def run(self):
        log(f"🚌 {self} arriving at stadium.")
        self.team_arrival_barrier.wait()
        log(f"🧳 {self} heads to locker room.")
        time.sleep(random.uniform(0.1, 0.4))

        log(f"🚶 {self} walking to tunnel.")
        self.field_barrier.wait()

        stadium.anthem_start.wait()
        for line in ANTHEM_LINES:
            log(f"🎶 {self} sings: {line}")
            time.sleep(0.03)

        stadium.match_start.wait()

        while not end_event.is_set():
            # Wait for next match tick, respecting pauses
            pause_event.wait()
            tick_event.wait(timeout=0.2)
            if end_event.is_set():
                break
            # If I own the ball, act; otherwise try foul/steal appropriately
            if ball.get_owner() is self:
                self.ball_handler_tick()
            else:
                # First: a single opposing DEF/MID may foul a FWD owner
                self.attempt_foul_on_forward_owner()
                # If no foul happened (or I'm not eligible), maybe steal
                self.attempt_steal_window()

        log(f"🏁 {self} done.")

# ---------------------------
# Build Teams & Roster
# ---------------------------

def build_team(name):
    team = Team(name)
    # 1 GK, 4 DEF, 4 MID, 2 FWD
    roles = [Role.GK] + [Role.DEF]*4 + [Role.MID]*4 + [Role.FWD]*2
    random.shuffle(roles)
    for i in range(1, TEAM_SIZE + 1):
        p = Player(team, f"P{i:02d}", roles[i-1], team.arrival_barrier, team.field_barrier)
        team.players.append(p)
    # Ensure exactly one GK
    gks = [p for p in team.players if p.role == Role.GK]
    if len(gks) == 0:
        team.players[0].role = Role.GK
    elif len(gks) > 1:
        for p in gks[1:]:
            p.role = Role.DEF
    return team

teamA = build_team("A")
teamB = build_team("B")

# ---------------------------
# Orchestration
# ---------------------------

class MatchOrchestrator:
    def __init__(self):
        self.clock = MatchClock(tick_event, end_event)

    def start(self):
        log("🚨 Simulation boot.")

        # Start fans
        fans = [Fan(i+1) for i in range(NUM_FANS)]
        for f in fans: f.start()

        time.sleep(0.4)
        log("🔓 Stadium gates OPEN.")
        stadium.gates_open.set()

        # Start players
        for p in teamA.players + teamB.players:
            p.start()

        # Anthem
        time.sleep(1.0)
        log("🎤 Anthem starts.")
        stadium.anthem_start.set()

        time.sleep(0.8)
        # Kickoff: random owner
        kickoff_owner = random.choice(teamA.players + teamB.players)
        ball.set_owner(kickoff_owner)
        log("🏟️ Match starts!")
        stadium.match_start.set()

        # Start clock
        self.clock.start()

        # Wait end
        end_event.wait()
        time.sleep(0.3)
        log(f"🔚 Final score: A {scoreboard['A']} - {scoreboard['B']} B")

def main():
    MatchOrchestrator().start()

if __name__ == "__main__":
    main()